import type { Metadata } from "next";
import "./globals.css";
import { Russo_One, Manrope, Montserrat } from "next/font/google";

const montserrat = Montserrat({
   subsets: ["latin"],
   variable: "--font-montserrat",
});

const russo = Russo_One({
   weight: "400",
   subsets: ["latin", "cyrillic"],
   variable: "--font-russo",
});

const manrope = Manrope({
   subsets: ["latin", "cyrillic"],
   weight: ["400", "500", "600", "800"],
   variable: "--font-manrope",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={`${montserrat.className} ${russo.variable} ${manrope.variable}`}
      >
         <body>{children}</body>
      </html>
   );
}
