import type { Metadata } from "next";
import { Russo_One, Manrope, Montserrat } from "next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
   subsets: ["latin"],
   variable: "--font-montserrat",
});

const russo = Russo_One({
   weight: "400",
   subsets: ["latin", "cyrillic"],
   variable: "--font-russo",
});

const manrope = Manrope({
   subsets: ["latin", "cyrillic"],
   weight: ["400", "500", "600", "800"],
   variable: "--font-manrope",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <div className="">
         <Header />
         {children}
         <Footer />
      </div>
   );
}
